# File 1 - java code

def right():
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here

def study():
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here

def raise():
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here

