# File 1 - java code

def worker():
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here

def difficult():
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here

# File 2 - java code

def vote():
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here

# File 3 - java code

def score():
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here

def item():
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here
    // Java code goes here

