# File 1 - c code

def politics():
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */
    /* C code goes here */

